apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: webapp
spec:
  containers:
  - name: app-container
    image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2:app
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
    #ip of mydql-pod
      value: 10.244.0.6
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: employees
    - name: DBPORT
      value: "3306"
