apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replica
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app-xinyueli
        image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2:my_app
        env:
        - name: DBHOST
          value: 10.244.0.5
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        ports:
        - containerPort: 8080
