apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: webapp
  labels:
    manifestType: pod
spec:
  containers:
  - name: app-container
    image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2:my_app
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: 10.244.0.13
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
