apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replica 
  namespace: webapp 
  labels:
    app: employees # Identifies the application to which this ReplicaSet belongs
    version: v1 
spec: # Specification of desired state for the ReplicaSet
  replicas: 3 
  selector: # Defines how the ReplicaSet identifies the Pods it is supposed to manage
    matchLabels:
      app: employees # Selector that matches the labels of the Pods
  template: # Template for creating the Pods
    metadata:
      labels: 
        app: employees
        version: v1
    spec: # Specification for the Pods
      containers: 
      - name: app-replica 
        image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2:my_app
        env: # Environment variables for the container
        - name: DBHOST
          value: "db-svc.sqldb.svc.cluster.local" # The value is the service name for database connectivity
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        ports: # List of ports to expose from the container
          - containerPort: 8080 # The container port to expose
