apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: employees