apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: webapp
  labels:
    app: webapp
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      containers:
        - name: app-container
          image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2:app
          env:
            - name: DBPWD
              value: "pw"
            - name: DBUSER
              value: "root"
            - name: DBHOST
              value: "db-svc.sqldb.svc.cluster.local"
            - name: DBPORT
              value: "3306"