apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: webapp
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: app-container
          image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/my_app
          env:
            - name: DBHOST
              value: 10.244.0.13
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "pw"
