apiVersion: v1  # Specifies the Kubernetes API version being used
kind: Pod  # Defines the type of Kubernetes resource being created, which is a Pod
metadata:
  name: mysql-db-pod  # Specifies the name of the Pod
  namespace: sqldb  # Specifies the namespace in which the Pod will be created
spec:
  containers:
  - name: mysql-xinyueli  # Specifies the name of the container within the Pod
    image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2:my_db  # Specifies the Docker image to use for the container
    env:
    - name: MYSQL_ROOT_USER  # Specifies the name of the environment variable
      value: "root"  # Specifies the value of the environment variable
    - name: MYSQL_ROOT_PASSWORD  # Specifies the name of another environment variable
      value: "pw"  # Specifies the value of the environment variable
    ports:
    - containerPort: 3306  # Specifies the port number to expose from the container
