apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db-replica
  namespace: sqldb
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  containers:
  - name: mysql-xinyueli
    image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2:my_db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306
